version: '3'

services:
    nginx:
      image: nginx:latest
      command: bash -c "cp /root/assignment_2/conf.d /etc/nginx/conf.d"
      ports:
        - 80:80
      depends_on:
        - backend

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        command: bash -c "
                 python /root/assignment_2/fresh_code/manage.py migrate &&
                 gunicorn fresh_code.durumi.wsgi -b 0.0.0.0:8000"
