# Generated by Django 3.2.9 on 2021-11-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salad', 'SALAD'), ('milk', 'MILK'), ('egg', 'EGG')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('isSold', models.BooleanField(default=False)),
                ('badge', models.CharField(choices=[('new', 'NEW'), ('old', 'OLD')], default='old', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('large', 'LARGE'), ('medium', 'MEDIUM'), ('small', 'SMALL')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('isSold', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.menu')),
            ],
        ),
    ]
